language: python
python:
- 2.6
- 2.7
- pypy
install:
- pip install Attest
script:
- python -mattest.run sidertests.tests
notifications:
  irc:
    channels:
    - "irc.freenode.net#sider"
    on_success: change
    on_failure: always
